const data = [
    "Paper",
    "Ink",
    "Textile",
    "Metal",
    "Oil paint",
    "Canvas",
    "Clay",
    "Graphite",
    "Photograph",
    "Pen",
    "Etching",
    "Engraving",
    "Gold",
    "Cotton",
    "Ceramic",
    "Wood",
    "Pencil",
    "Glass",
    "Silver",
    "Stoneware",
    "Pigment",
    "Bronze",
    "Gouache",
    "Feather",
    "Colored pencil",
    "Tempera",
    "Silk",
    "Acrylic paint",
    "Porcelain",
    "Iron",
    "Copper",
    "Plastic",
    "Steel",
    "Jade",
    "Aluminium",
    "Wool",
    "Leather",
    "Lead",
    "Stainless steel",
    "Marble",
    "Wire",
    "Cardboard",
    "Brass",
    "Sand",
    "Linen",
    "Vitreous enamel",
    "Yarn",
    "Concrete",
    "Chalk",
    "Wax",
    "Lace",
    "Polyester",
    "Plaster",
    "Lacquer",
    "Charcoal",
    "Photographic film",
    "Brick",
    "Platinum",
    "Nylon",
    "Rope",
    "Diamond",
    "Titanium",
    "Velvet",
    "Resin",
    "Latex",
    "Sheet metal",
    "Crayon",
    "Quartz",
    "Felt",
    "Varnish",
    "Oak",
    "Terracotta",
    "Walnut",
    "Polyurethane",
    "Plywood",
    "Cast iron",
    "Polypropylene",
    "Gold leaf",
    "Granite",
    "Epoxy",
    "Limestone",
    "Stained glass",
    "Mercury",
    "Ivory",
    "Stucco",
    "Oil pastel",
    "Gauze",
    "Mahogany",
    "Sandstone",
    "Amber",
    "Seashell",
    "Beeswax",
    "Jute",
    "Wrought iron",
    "Slate",
    "Onyx",
    "Newsprint",
    "Garnet",
    "Sawdust",
    "Nacre",
    "Hessian fabric",
    "Ebony",
    "Acrylic paint",
    "Acrylic resin",
    "Adhesive",
    "Agate",
    "Alabaster",
    "Aluminium",
    "Amber",
    "Amethyst",
    "Andesite",
    "Azurite",
  ];
  const clear=['Textile', 'Photograph', 'Ceramic', 'Pigment', 'Colored pencil', 'Acrylic paint', 'Aluminium', 'Stainless steel', 'Sand', 'Vitreous enamel', 'Yarn', 'Polyester', 'Photographic film', 'Nylon', 'Titanium', 'Latex', 'Crayon', 'Quartz', 'Varnish', 'Polyurethane', 'Polypropylene', 'Epoxy', 'Oil pastel', 'Seashell', 'Newsprint', 'Nacre', 'Hessian fabric', 'Acrylic paint', 'Acrylic resin', 'Adhesive', 'Aluminium']
  data.filter((item,index)=>{
      return !clear.includes(item)
  })
  export default data;